/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ClientesController;
import Model.Clientes;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ariel
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    private final ClientesController controller;

    public TelaHome() {
        initComponents();
        controller = new ClientesController();
        carregarClientes();
    }

    private void carregarClientes() {
        try {
            List<Clientes> listaClientes = controller.listarClientes();
            DefaultTableModel model = (DefaultTableModel) tableTelaInicial.getModel();
            model.setRowCount(0); // Limpa a tabela
            for (Clientes cliente : listaClientes) {
                model.addRow(new Object[]{
                    cliente.getId(), cliente.getNome(), obterNomeStatus(cliente.getIdStatus())
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar clientes: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirTelaGerenciarClientes() {
        TelaGerenciarClientes telaGerenciarClientes = new TelaGerenciarClientes();
        telaGerenciarClientes.setVisible(true); // Abre a tela
    }

    private void pesquisarCliente() {
        try {
            String nome = JOptionPane.showInputDialog(this, "Digite o nome do cliente:", "Pesquisar Cliente", JOptionPane.QUESTION_MESSAGE);

            if (nome != null && !nome.isEmpty()) {
                List<Clientes> listaClientes = controller.pesquisarClientePorNome(nome);

                if (listaClientes.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Nenhum cliente encontrado!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    DefaultTableModel model = (DefaultTableModel) tableTelaInicial.getModel();
                    model.setRowCount(0);
                    for (Clientes cliente : listaClientes) {
                        model.addRow(new Object[]{
                            cliente.getId(), cliente.getNome(), obterNomeStatus(cliente.getIdStatus())
                        });
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar cliente: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String obterNomeStatus(int idStatus) {
        switch (idStatus) {
            case 0:
                return "Negativado";
            case 1:
                return "CDL";
            case 2:
                return "Pequenas Causas";
            case 3:
                return "Acordo";
            default:
                return "Desconhecido";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableTelaInicial = new javax.swing.JTable();
        btGerenciarClientes = new javax.swing.JButton();
        btStatusCliente = new javax.swing.JButton();
        btPesquisaCliente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableTelaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null
                }},
                new String [] {
                    "Código", "Cliente", "Status"
                }
            ){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Impede a edição das células
                }
            }
        );
        DefaultTableModel model = (DefaultTableModel) tableTelaInicial.getModel();
        model.addRow(new Object[]{"001", "Ariel", "Ativo"});
        tableTelaInicial.setShowGrid(true);
        tableTelaInicial.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(tableTelaInicial);

        btGerenciarClientes.setText("Gerenciar Clientes");
        btGerenciarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarClientesActionPerformed(evt);
            }
        });

        btStatusCliente.setText("Status");

        btPesquisaCliente.setText("Pesquisar Cliente");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btGerenciarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(btStatusCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPesquisaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btGerenciarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btStatusCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerenciarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarClientesActionPerformed
        TelaGerenciarClientes telaGerenciarClientes = new TelaGerenciarClientes();
        telaGerenciarClientes.setVisible(true); 
        telaGerenciarClientes.setLocationRelativeTo(this);
    }//GEN-LAST:event_btGerenciarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerenciarClientes;
    private javax.swing.JButton btPesquisaCliente;
    private javax.swing.JButton btStatusCliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableTelaInicial;
    // End of variables declaration//GEN-END:variables
}
